apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1.1
  labels:
    app: nginx-1.1
    env: prod

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-1.1
      env: prod
  template:
    metadata:
      labels:
        app: nginx-1.1
        env: prod
    spec:
      containers:
        - name: nginx
          image: cammey20/amar_custom_nginx:latest
          ports:
            - containerPort: 80
